### PR TITLE
[WIP]: Improve json information

### LINKED ISSUE #91: Add more details to JSON output
#### 1. If I have two contract definitions in a file e.g.
```javascript
contract C {
function i_am_backdoor(){}
}

contract D {
function i_am_backdoor(){
}
}
```
The json output doesn't tell me which of the contracts the function in the output belong to
The JSON output looks something like this
```js
{  
      "check":"backdoor",
      "function":{  
         "name":"i_am_a_backdoor",
         "source_mapping":{  
            "start":43,
            "length":74,
            "filename":"/tmp/browser/suicide.sol",
            "lines":[  
               5,
               6,
               7
            ]
         }
      }
   }
```
it doesn't indicate which contract it belongs to.

#### 2. Add Error Message
It would be great to have the error log messages displayed in the terminal as part of the JSON output.
The current implementation requires having to parse the details and reconstructing the messages.

These two changes are needed for the Slither Remix plugin

### PR DESCRIPTION
**Pull request by montyly**
- Add `description` field for each report (which contains the txt description)
 - Add [`contract`](https://github.com/trailofbits/slither/wiki/JSON-output#contract) field to [`function`](https://github.com/trailofbits/slither/wiki/JSON-output#function) field 

Close #91

- [ ] Update json documentation

### CODE REVIEW

**Comment by montyly** [comment]
Potential other changes:
- Add an `impact` field
- Add a `confidence` field

**Comment by samparsky** [comment]
@montyly I had actually worked on something similar but yeah this is great

**Comment by samparsky** [comment]
And yeah adding impact & confidence fields would be helpful too

**Comment by samparsky** [comment]
@monthly Waiting on this PR to get merged to finalize the remix plugin

**Comment by samparsky** [comment]
@montyly a daily reminder that I am waiting for this to get merged 😄

**Pull request merged**
